//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzendaHours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReactView
    {
        public int EntryId { get; set; }
        public string EmployeeId { get; set; }
        public string Project { get; set; }
        public string Task { get; set; }
        public string CaseNo { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string WikiLink { get; set; }
        public System.DateTime RecordDate { get; set; }
    }
}
